### ISSUE TITLE
Trying out sample code of pbcvt on Anaconda prompt

### ISSUE THREAD

**Issue by pratikshaandhare** [Algomorph/pyboostcvconverter#17]
Hi, 

I had created pbcvt.cp36-win_amd64.pyd by successful build of ALL_BUILD created by CMake. I had used configuration type as .lib in pbcvt project. I installed pyton 3.6.4 by anaconda prompt. I had given the path where pbcvt.cp36-win_amd64.pyd is present and I am tring to import pbcvt. But it is showing error as shown in screenshot. I installed python3.6.4 64 bit and the pyd generated from the platform of visual studio 2017 is also x64. Still facing issue for import pbcvt. Can you please advise me?

![issue](https://user-images.githubusercontent.com/20615346/40781929-553c7e1e-64fb-11e8-978c-cb24a20eb85a.png)

I had also tried to generate pbcvt.cp36-win_amd64.pyd by the configuration type as .dll in pbcvt project. I had define BOOST_PYTHON_STATIC_LIB. But still I am getting unresolved external symbol error while building it. Can you please help me out? 

Thanks

**Comment by Algomorph** [comment]
.pyd is a dynamic library, so in theory, it should suffice. I was wrong to say earlier that it has to be .dll. Please try to revert to the .pyd build.

The error you're getting earlier, i.e. %1 is not a valid Win32 application, could be stemming from architecture mismatch between your python and the .pyd you compiled.  Could you check what architecture your python is using?

You can do so by running ```import ctypes; print(32 if ctypes.sizeof(ctypes.c_voidp)==4 else 64, 'bit CPU')``` in the python shell.

**Comment by pratikshaandhare** [comment]
Thanks a lot. The architecture of python is 64 bit and the .pyd is generated by building ALL_BUILD on visual studio 2017 of the configuration Release x64.

**Comment by Algomorph** [comment]
A few more things to check:
1) In order for the installation scripts to work properly (which simply copy the .pyd to the correct directory with the correct name, the INSTALL project in VisualStudio must be built. It should report where it copied the .pyd file to in VS output prompt. Then, it makes sense to check if that is the correct location, i.e. the .pyd must end up in python path. To do so, in your python shell, run ```import sys; print('\n'.join(sys.path))```, and check to see if the location is listed.
2) In order for the library to load correctly into python, all of the .dll dependencies it has must be satisfied. This means that opencv dynamic libraries (and boost libraries, in case you built them in shared/dynamic mode) need to be in the system path. A surefire way to check is to open the location where the .pyd was copied in windows explorer and drag it into [Dependency Walker](http://www.dependencywalker.com/). The first-level set of libraries in the hierarchy that it shows should be discovered, i.e. it should give you the actual locations of the .dll files instead of question marks.

Please perform these checks and see if you still have the problem.

**Comment by pratikshaandhare** [comment]
Thank you very much for the suggestions. 

1.   I had done ALL_BUILD build and also INSTALL build. The pbcvt.pyd is generated at ..\pyboostcvconverter-master\build\Release. I had copied this pbcvt.pyd at the location which is listed under system path i.e ..\Anaconda3. But it is showing same error on command prompt for import pbcvt.

2. I had checked pyd file in dependency walker, but it is showing Error: At least one file was not a 32-bit or 64-bit Windows module.

**Comment by Algomorph** [comment]
1. It seems incorrect that the INSTALL target didn't copy the .pyd (it should have copied the one in \Release to your Anaconda's site-packages folder). Please verify that in, CMake GUI, all the parameters starting with PYTHON are filled in and correct (you can check **Grouped** and **Advanced** for this). A good way to proceed: download & install python 3.6 x64 from the [official website](https://www.python.org/), clear your CMake cache from CMake GUI, reconfigure, recompile, see if it works there, and, if it does, take note of the PYTHON CMake parameters. Then you can uninstall and go back to the Anaconda distro, rerun CMake, and compare.

2. Looks like something could be wrong with your compiler/build, because loading the .pyd into Dependency Walker shows a similar error as the import. Unfortunately, there is no way I can replicate this on my Windows box.
Perhaps, try a different version of VisualStudio? I was testing on VS2017 Community Edition (corresponds to MSVC 14.1).

**Comment by pratikshaandhare** [comment]
Thanks a lot. 

It is resolved now. I am able to run sample code by Anaconda prompt. 
 
>>>> import pbcvt
>>> import numpy
>>> a = numpy.array([[1., 2., 3.]])
>>> b = numpy.array([[1.],
...                  [2.],
...                  [3.]])
>>> print(pbcvt.dot(a, b))
[[14.]]
>>> print(pbcvt.dot2(a, b))
[[14.]]
>>>

The configuration type is .dll for creating .pyd file in pbcvt project's property page and checked for ../boost/libs in linker. This resolved the issue.

**Comment by Algomorph** [comment]
@pratikshaandhare , I'm glad you resolved the issue. I'm guessing this may stem that some of the new boost libraries now do a weird thing in Windows, where they include processor linker commands (not standard in C++) which try to link to 'someboostlib.lib' without the full path, i.e. the actual absolute path to the .lib file that is added through CMake doesn't work. I'm going to be looking into making a CMake work-around for this soon. For now, the work-around is to simply add the absolute path to the boost/libs folder in the "Additional Library Directories" to the .pbcvt project in Visual Studio.
