### ISSUE TITLE
undefined symbol: _ZNK2cv12MatAllocator3mapEPNS_8UMatDataEi

### ISSUE THREAD

**Issue by fabianbormann** [Algomorph/pyboostcvconverter#6]
Hi,

I followed the instruction:

``` zsh
git clone https://github.com/Algomorph/pyboostcvconverter.git 
mkdir build
cd build
cmake ..
make
```

and it builds with no errors/warnings.
I renamed the generated pbcvt.cpython-35m-x86_64-linux-gnu.so to pbcvt.so

but when I try to load it in python

``` python
>>> import pbcvt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ./pbcvt.so: undefined symbol: _ZTIN2cv12MatAllocatorE
```

It seems that there are some linker errors? Did I miss something?
I'm on a Ubuntu 15.10 and I use Python 2.7.10, OpenCV 3.1.0.

Thank you!

**Comment by Algomorph** [comment]
Firstly, you shouldn't need to rename the generated .so file. If you're getting that filename, that probably means your PYTHON_DESIRED_VERSION is set to 3.X.  Try passing it the right one, i.e.:
cmake ... -DPYTHON_DESIRED_VERSION:STRING=2.X (fill in ... with your source directory if need be).

Btw, for the 3.X it works without renaming, i.e. python shell, here is what I see:

```
In [1]: import pbcvt

In [2]: pbcvt.__file__
Out[2]: '/usr/local/lib/python3.5/dist-packages/pbcvt.cpython-35m-x86_64-linux-gnu.so'
```

For the future, I highly recommend using cmake-gui (Ubuntu package cmake-qt-gui) with the "Grouped" and "Advanced" options to examine the CMake cached stuff before you compile.

Please close this issue if your problem is solved.

**Comment by fabianbormann** [comment]
:+1:  nice thank you so much! cmake-gui with setting PYTHON_DESIRED_VERSION to 2.X worked for me!
